# Generated by Django 6.0.1 on 2026-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField(verbose_name='공격자 카드')),
                ('defender_card', models.IntegerField(blank=True, null=True, verbose_name='수비자 카드')),
                ('result', models.CharField(default='진행중', max_length=10, verbose_name='게임 결과')),
                ('win_criterion', models.IntegerField(blank=True, choices=[(0, '큰 수 승리'), (1, '작은 수 승리')], null=True, verbose_name='승리 기준')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 시간')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
