# Generated by Django 6.0.1 on 2026-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win_criterion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
