# Generated by Django 6.0.1 on 2026-01-19 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정 시간'),
        ),
        migrations.AlterField(
            model_name='game',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_games', to=settings.AUTH_USER_MODEL, verbose_name='공격자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='attacker_card',
            field=models.IntegerField(verbose_name='공격자 카드'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_games', to=settings.AUTH_USER_MODEL, verbose_name='수비자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='수비자 카드'),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(default='진행중', max_length=10, verbose_name='게임 결과'),
        ),
        migrations.AlterField(
            model_name='game',
            name='win_criterion',
            field=models.IntegerField(blank=True, choices=[(0, '큰 수 승리'), (1, '작은 수 승리')], null=True, verbose_name='승리 기준'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL, verbose_name='승리자'),
        ),
    ]
