# Generated by Django 6.0.1 on 2026-01-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win_criterion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
